name: Essential files modified

<<<<<<< HEAD
permissions:
  contents: write

=======
>>>>>>> 7278a0db3a (Revert "[miryoku-github] Delete upstream github files")
on:
  push:
    branches:
    - master
    paths:
<<<<<<< HEAD
    - builddefs/**/*
    - drivers/**/*
    - platforms/**/*
    - quantum/**/*
    - tests/**/*
    - tmk_core/**/*
    - util/**/*
=======
    - quantum/**/*
    - tmk_core/**/*
    - drivers/**/*
    - tests/**/*
    - util/**/*
    - platforms/**/*
>>>>>>> 7278a0db3a (Revert "[miryoku-github] Delete upstream github files")
    - Makefile
    - '*.mk'

jobs:
  tag:
    runs-on: ubuntu-latest

    # protect against those who develop with their fork on master
    if: github.repository == 'qmk/qmk_firmware'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
<<<<<<< HEAD
      uses: anothrNick/github-tag-action@1.61.0
=======
      uses: anothrNick/github-tag-action@1.52.0
>>>>>>> 7278a0db3a (Revert "[miryoku-github] Delete upstream github files")
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: 'patch'
