name: CLI CI

<<<<<<< HEAD
permissions:
  contents: read

=======
>>>>>>> 7278a0db3a (Revert "[miryoku-github] Delete upstream github files")
on:
  push:
    branches:
    - master
    - develop
  pull_request:
    paths:
    - 'lib/python/**'
    - 'requirements.txt'
    - '.github/workflows/cli.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: pip3 install -r requirements-dev.txt
    - name: Run tests
      run: qmk pytest
